services:
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 5

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql/init2_customer_shipping.sql:/docker-entrypoint-initdb.d/init2_customer_shipping.sql

    order:
        build:
            context: ./order
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: OrderServiceDB
        volumes:
            - ./customer_data.csv:/app/customer_data.csv
        restart: unless-stopped
        ports:
            - "5000:5000"
        depends_on:
            rabbitmq:
                condition: service_healthy

    warehouse:
        build:
            context: ./warehouse
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: WarehouseServiceDB
        restart: unless-stopped
        ports:
            - "5100:5100"
        depends_on:
            rabbitmq:
                condition: service_healthy

    payment:
        build:
            context: ./payment
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: PaymentServiceDB
        restart: unless-stopped
        ports:
            - "5001:5001"
    catalog:
        build:
            context: ./catalog
        environment:
            RABBITMQ_URL: amqp://rabbitmq
        restart: unless-stopped
        ports:
            - "5002:5000"
        depends_on:
            rabbitmq:
                condition: service_healthy

    customer:
        build:
            context: ./customer
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: CustomerServiceDB
        volumes:
            - ./customer_data.csv:/app/customer_data.csv
        restart: unless-stopped
        ports:
            - "5003:5003"
        depends_on:
            rabbitmq:
                condition: service_healthy

volumes:
    rabbitmq_data:
    mysql_data:
