services:
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 5

    mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    order:
        build:
            context: ./order
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: OrderServiceDB
        restart: unless-stopped
        ports:
            - "5000:5000"
        depends_on:
            rabbitmq:
                condition: service_healthy

    warehouse:
        build:
            context: ./warehouse
        environment:
            RABBITMQ_URL: amqp://rabbitmq
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: root
            DB_NAME: WarehouseServiceDB
        restart: unless-stopped
        depends_on:
            rabbitmq:
                condition: service_healthy

volumes:
  rabbitmq_data:
  mysql_data:
